# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
