# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160307_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_alcohol',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
