# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160307_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_alcohol',
            field=models.CharField(max_length=30),
        ),
    ]
