# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160308_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
