# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_suggestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suggestions',
            field=models.ManyToManyField(related_name='user_suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
